test:
  mysql41: 9307

production:
  pid_file: /home/buildfpv/shared/tmp/searchd.pid
  indices_location: /home/buildfpv/shared/db/sphinx
  configuration_file: /home/buildfpv/shared/production.sphinx.conf
  binlog_path: /home/buildfpv/shared/binlog
