test:
  mysql41: 9307

production:
  mysql41: 9306
  pid_file: /home/deploy/buildfpv/shared/tmp/pids/searchd.pid
  indices_location: /home/deploy/buildfpv/shared/db/sphinx
  configuration_file: /home/deploy/buildfpv/shared/production.sphinx.conf
  binlog_path: /home/deploy/buildfpv/shared/binlog
